version: '3'

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - '8040:8000'
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8.0
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --pid-file=/var/run/mysqld/mysqld.pid

    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './docker/mysql:/var/run/mysqld'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3309